#Requires -Version 7
# Tears down the local BinStash dev instance:
#   - stops & removes the PostgreSQL container AND its data volume,
#   - deletes the local chunk-store storage and generated setup state.
#
# This removes the running instance only; the harness scripts stay in place
# (they are committed). The chunk-store storage it deletes is regenerated by
# the next up.ps1 + setup.ps1 run.
#
# The CLI also persists auth tokens outside this folder, in
# %APPDATA%\BinStash\Cli\auth.dat. Clear them with:
#   pwsh tooling/dev-instance/cli.ps1 auth logout-all
$ErrorActionPreference = 'Stop'
$dev = $PSScriptRoot

Write-Host 'Stopping and removing PostgreSQL container + volume...' -ForegroundColor Cyan
docker compose -f (Join-Path $dev 'compose.yaml') down -v

$storage = Join-Path $dev 'storage'
if (Test-Path $storage) {
    Remove-Item -Recurse -Force $storage
    Write-Host "Removed $storage"
}

Write-Host ''
Write-Host 'Dev instance removed.' -ForegroundColor Green
Write-Host 'Optional: clear stored CLI tokens with  pwsh tooling/dev-instance/cli.ps1 auth logout-all'
