query ServiceAccounts($first: Int, $after: String, $where: ServiceAccountGqlFilterInput) {
  serviceAccounts(first: $first, after: $after, where: $where, order: [{ name: ASC }]) {
    totalCount
    pageInfo { hasNextPage endCursor }
    nodes { id name createdAt }
  }
}

query ServiceAccountApiKeys($serviceAccountId: UUID!) {
  serviceAccountApiKeys(serviceAccountId: $serviceAccountId) {
    id displayName createdAt expiresAt lastUsedAt isActive scopes
  }
}

mutation CreateServiceAccount($input: CreateServiceAccountInput!) {
  createServiceAccount(input: $input) { id name createdAt }
}

mutation UpdateServiceAccount($input: UpdateServiceAccountInput!) {
  updateServiceAccount(input: $input) { id name createdAt }
}

mutation DeleteServiceAccount($accountId: UUID!) {
  deleteServiceAccount(accountId: $accountId)
}

mutation CreateServiceAccountApiKey($serviceAccountId: UUID!, $input: CreateServiceAccountApiKeyInput!) {
  createServiceAccountApiKey(serviceAccountId: $serviceAccountId, input: $input) {
    displayName
    key
    expiresAt
  }
}

mutation DeleteServiceAccountApiKey($serviceAccountId: UUID!, $apiKeyId: UUID!) {
  deleteServiceAccountApiKey(serviceAccountId: $serviceAccountId, apiKeyId: $apiKeyId)
}
