// <auto-generated />
using System;
using BinStash.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BinStash.Infrastructure.Data.Migrations
{
    [DbContext(typeof(BinStashDbContext))]
    [Migration("20250929152604_SwitchReleaseDefinisionChecksumToHash32BackedByBytea")]
    partial class SwitchReleaseDefinisionChecksumToHash32BackedByBytea
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BinStash.Core.Entities.Chunk", b =>
                {
                    b.Property<Guid>("ChunkStoreId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Checksum")
                        .HasColumnType("bytea");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.HasKey("ChunkStoreId", "Checksum");

                    b.ToTable("Chunks", null, t =>
                        {
                            t.HasCheckConstraint("chk_chunks_checksum_len", "octet_length(\"Checksum\") = 32");
                        });
                });

            modelBuilder.Entity("BinStash.Core.Entities.ChunkStore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("ChunkStores", (string)null);
                });

            modelBuilder.Entity("BinStash.Core.Entities.FileDefinition", b =>
                {
                    b.Property<Guid>("ChunkStoreId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("Checksum")
                        .HasColumnType("bytea");

                    b.Property<long>("Length")
                        .HasColumnType("bigint");

                    b.HasKey("ChunkStoreId", "Checksum");

                    b.ToTable("FileDefinitions", null, t =>
                        {
                            t.HasCheckConstraint("chk_file_definitions_checksum_len", "octet_length(\"Checksum\") = 32");
                        });
                });

            modelBuilder.Entity("BinStash.Core.Entities.IngestSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("ChunksSeenNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ChunksSeenTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ChunksSeenUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("DataSizeTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("DataSizeUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FilesSeenNew")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("FilesSeenTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("FilesSeenUnique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("LastUpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MetadataSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RepoId");

                    b.HasIndex("State");

                    b.ToTable("IngestSessions", (string)null);
                });

            modelBuilder.Entity("BinStash.Core.Entities.Release", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CustomProperties")
                        .HasColumnType("jsonb");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<byte[]>("ReleaseDefinitionChecksum")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("RepoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("RepoId");

                    b.ToTable("Releases", (string)null);
                });

            modelBuilder.Entity("BinStash.Core.Entities.ReleaseMetrics", b =>
                {
                    b.Property<Guid>("ReleaseId")
                        .HasColumnType("uuid");

                    b.Property<int>("ChunksInRelease")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("ComponentsInRelease")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("FilesInRelease")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("IngestSessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("MetaBytesFull")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("MetaBytesFullDiff")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("NewChunks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("NewCompressedBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalUncompressedSize")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)")
                        .HasDefaultValue(0m);

                    b.HasKey("ReleaseId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IngestSessionId")
                        .IsUnique();

                    b.ToTable("ReleaseMetrics", (string)null);
                });

            modelBuilder.Entity("BinStash.Core.Entities.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<Guid>("ChunkStoreId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ChunkStoreId");

                    b.ToTable("Repositories", (string)null);
                });

            modelBuilder.Entity("BinStash.Core.Entities.ChunkStore", b =>
                {
                    b.OwnsOne("BinStash.Core.Entities.ChunkerOptions", "ChunkerOptions", b1 =>
                        {
                            b1.Property<Guid>("ChunkStoreId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("AvgChunkSize")
                                .HasColumnType("integer")
                                .HasColumnName("Chunker_AvgChunkSize");

                            b1.Property<int?>("BoundaryCheckBytes")
                                .HasColumnType("integer")
                                .HasColumnName("Chunker_BoundaryCheckBytes");

                            b1.Property<int?>("MaxChunkSize")
                                .HasColumnType("integer")
                                .HasColumnName("Chunker_MaxChunkSize");

                            b1.Property<int?>("MinChunkSize")
                                .HasColumnType("integer")
                                .HasColumnName("Chunker_MinChunkSize");

                            b1.Property<int?>("ShiftCount")
                                .HasColumnType("integer")
                                .HasColumnName("Chunker_ShiftCount");

                            b1.Property<int>("Type")
                                .HasColumnType("integer")
                                .HasColumnName("Chunker_Type");

                            b1.HasKey("ChunkStoreId");

                            b1.ToTable("ChunkStores");

                            b1.WithOwner()
                                .HasForeignKey("ChunkStoreId");
                        });

                    b.Navigation("ChunkerOptions")
                        .IsRequired();
                });

            modelBuilder.Entity("BinStash.Core.Entities.IngestSession", b =>
                {
                    b.HasOne("BinStash.Core.Entities.Repository", "Repository")
                        .WithMany()
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("BinStash.Core.Entities.Release", b =>
                {
                    b.HasOne("BinStash.Core.Entities.Repository", "Repository")
                        .WithMany("Releases")
                        .HasForeignKey("RepoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("BinStash.Core.Entities.ReleaseMetrics", b =>
                {
                    b.HasOne("BinStash.Core.Entities.IngestSession", "IngestSession")
                        .WithOne()
                        .HasForeignKey("BinStash.Core.Entities.ReleaseMetrics", "IngestSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IngestSession");
                });

            modelBuilder.Entity("BinStash.Core.Entities.Repository", b =>
                {
                    b.HasOne("BinStash.Core.Entities.ChunkStore", "ChunkStore")
                        .WithMany()
                        .HasForeignKey("ChunkStoreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChunkStore");
                });

            modelBuilder.Entity("BinStash.Core.Entities.Repository", b =>
                {
                    b.Navigation("Releases");
                });
#pragma warning restore 612, 618
        }
    }
}
